#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : blender
Version  : 2.79b
Release  : 11
URL      : http://download.blender.org/source/blender-2.79b.tar.gz
Source0  : http://download.blender.org/source/blender-2.79b.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.1 OFL-1.0 Zlib
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : cmake
BuildRequires : eigen-dev
BuildRequires : fftw-dev
BuildRequires : freeglut-dev
BuildRequires : freetype-dev
BuildRequires : git
BuildRequires : glew-dev
BuildRequires : glibc-dev
BuildRequires : glu-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libsndfile-dev
BuildRequires : mesa-dev
BuildRequires : numpy
BuildRequires : oiio-dev
BuildRequires : openal-soft-dev
BuildRequires : openblas
BuildRequires : openexr-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xi)
BuildRequires : python3
BuildRequires : python3-core
BuildRequires : python3-dev
BuildRequires : requests
BuildRequires : tiff-dev
BuildRequires : zlib-dev
Patch1: build.patch

%description
Files:
logImageLib.h, logImageLib.c: combined cineon/dpx image library
dpxlib.h, dpxlib.c: dpx specific library
dpxfile.h: dpx file structure
cineonlib.h, cineonlib.c: cineon specific library
cineonfile.h: cineon file structure
logImageCore.h, logImageCore.c: log image routines common to cineon amd dpx

%prep
%setup -q -n blender-2.79b
%patch1 -p1
pushd ..
cp -a blender-2.79b buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537284689
mkdir clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%cmake .. -DWITH_INSTALL_PORTABLE=OFF -DWITH_BUILDINFO=OFF -DPYTHON_VERSION=3.7 -DWITH_CYCLES=ON -DWITH_FFTW3=ON -DWITH_LINKER_GOLD=OFF
make  %{?_smp_mflags}
popd
mkdir clr-build-avx2
pushd clr-build-avx2
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -march=haswell "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -march=haswell "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
%cmake .. -DWITH_INSTALL_PORTABLE=OFF -DWITH_BUILDINFO=OFF -DPYTHON_VERSION=3.7 -DWITH_CYCLES=ON -DWITH_FFTW3=ON -DWITH_LINKER_GOLD=OFF
make VERBOSE=1  %{?_smp_mflags}  || :
popd

%install
export SOURCE_DATE_EPOCH=1537284689
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/blender
cp COPYING %{buildroot}/usr/share/doc/blender/COPYING
cp build_files/package_spec/debian/copyright %{buildroot}/usr/share/doc/blender/build_files_package_spec_debian_copyright
cp extern/carve/LICENSE.GPL2 %{buildroot}/usr/share/doc/blender/extern_carve_LICENSE.GPL2
cp extern/carve/LICENSE.GPL3 %{buildroot}/usr/share/doc/blender/extern_carve_LICENSE.GPL3
cp extern/ceres/LICENSE %{buildroot}/usr/share/doc/blender/extern_ceres_LICENSE
cp extern/cuew/LICENSE %{buildroot}/usr/share/doc/blender/extern_cuew_LICENSE
cp extern/gflags/COPYING.txt %{buildroot}/usr/share/doc/blender/extern_gflags_COPYING.txt
cp extern/glog/COPYING %{buildroot}/usr/share/doc/blender/extern_glog_COPYING
cp extern/gmock/LICENSE %{buildroot}/usr/share/doc/blender/extern_gmock_LICENSE
cp extern/gtest/LICENSE %{buildroot}/usr/share/doc/blender/extern_gtest_LICENSE
cp extern/libopenjpeg/license.txt %{buildroot}/usr/share/doc/blender/extern_libopenjpeg_license.txt
cp extern/lzo/minilzo/COPYING %{buildroot}/usr/share/doc/blender/extern_lzo_minilzo_COPYING
cp extern/recastnavigation/License.txt %{buildroot}/usr/share/doc/blender/extern_recastnavigation_License.txt
cp intern/audaspace/COPYING %{buildroot}/usr/share/doc/blender/intern_audaspace_COPYING
cp intern/elbeem/COPYING %{buildroot}/usr/share/doc/blender/intern_elbeem_COPYING
cp intern/elbeem/COPYING_trimesh2 %{buildroot}/usr/share/doc/blender/intern_elbeem_COPYING_trimesh2
cp intern/smoke/intern/LICENSE.txt %{buildroot}/usr/share/doc/blender/intern_smoke_intern_LICENSE.txt
cp release/datafiles/LICENSE-bfont.ttf.txt %{buildroot}/usr/share/doc/blender/release_datafiles_LICENSE-bfont.ttf.txt
cp release/datafiles/LICENSE-bmonofont-i18n.ttf.txt %{buildroot}/usr/share/doc/blender/release_datafiles_LICENSE-bmonofont-i18n.ttf.txt
cp release/datafiles/LICENSE-droidsans.ttf.txt %{buildroot}/usr/share/doc/blender/release_datafiles_LICENSE-droidsans.ttf.txt
cp release/datafiles/matcaps/license.txt %{buildroot}/usr/share/doc/blender/release_datafiles_matcaps_license.txt
cp release/text/copyright.txt %{buildroot}/usr/share/doc/blender/release_text_copyright.txt
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64/haswell/avx512_1
cp clr-build/lib/* %{buildroot}/usr/lib64/
cp clr-build-avx2/lib/* %{buildroot}/usr/lib64/haswell
## install_append end

%files
%defattr(-,root,root,-)
